// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// ultrasonic //
// ---------- //

#define ultrasonic_wrap_target 0
#define ultrasonic_wrap 15
#define ultrasonic_pio_version 0

static const uint16_t ultrasonic_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xff01, //  1: set    pins, 1                [31]
    0xe000, //  2: set    pins, 0
    0x2020, //  3: wait   0 pin, 0
    0x20a0, //  4: wait   1 pin, 0
    0xa02b, //  5: mov    x, ~null
    0x00c8, //  6: jmp    pin, 8
    0x0009, //  7: jmp    9
    0x0046, //  8: jmp    x--, 6
    0xa0c9, //  9: mov    isr, ~x
    0x8000, // 10: push   noblock
    0xe03f, // 11: set    x, 31
    0xe05f, // 12: set    y, 31
    0xbf42, // 13: nop                           [31]
    0x008d, // 14: jmp    y--, 13
    0x004c, // 15: jmp    x--, 12
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ultrasonic_program = {
    .instructions = ultrasonic_program_instructions,
    .length = 16,
    .origin = -1,
    .pio_version = ultrasonic_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ultrasonic_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ultrasonic_wrap_target, offset + ultrasonic_wrap);
    return c;
}
#endif

